events:
  - name: "The Prodigy"
    slug: "prodigy-2026"
    enabled: true                    # set false to skip this event completely
    telegram_enabled: false           # set false to collect data without Telegram message
    currency_code: "EUR"
    currency_symbol: "€"
    event_date: "2026-06-27"         # date of the event (for forecasting)
    telegram_chat_id: "-5227089558"  # Telegram group/chat ID for daily reports
    report_base_url: "https://pavelserb.github.io/ntrtickets"
    sales_target:
      tickets: 6500       # target number of tickets (set when known)
      revenue: 422500       # target revenue in EUR (set when known)
    sources:
      - type: mticket
        provider_name: "mticket"
        provider_link: "mticket.eu"
        event_page_url: "https://lv.mticket.eu/en/riga/the-prodigy-riga-1538.html"
        params:
          event_id: "173167"
      - type: bilesu_serviss
        provider_name: "Biļešu Serviss"
        provider_link: "bilesuserviss.lv"
        event_page_url: "https://www.bilesuserviss.lv/biletes/3HKOANTH2L/the-prodigy"
        params:
          event_id: "496539"
          legal_person_id: "4003"
          sale_start: "2026-03-17"
  - name: "Andrea Bocelli"
    slug: "bocelli-2026"
    enabled: true                    # set false to skip this event completely
    telegram_enabled: true           # set false to collect data without Telegram message
    currency_code: "TRY"
    currency_symbol: "₺"
    event_date: "2026-05-30"         # date of the event (for forecasting)
    telegram_chat_id: "-3368114749"  # Telegram group/chat ID for daily reports
    report_base_url: "https://pavelserb.github.io/ntrtickets"
    sales_target:
      tickets: 23000       # target number of tickets (set when known)
      revenue: 250000000       # target revenue in EUR (set when known)
    sources:
      - type: mticket
        provider_name: "mticket"
        provider_link: "mticket.com.tr"
        event_page_url: "https://mticket.com.tr/tr/istanbul/andrea-bocelli-romanza-30th-anniversary-world-tour-3594.html"
        params:
          event_id: "100182530"
      - type: passo
        provider_name: "Passo"
        provider_link: "passo.com.tr"
        event_page_url: "https://www.passo.com.tr/en/event/andrea-bocelli-besiktas-tupras-stadyumu-biletleri/10738366"
        params:
          report_id: "8cfa7732-52a3-4869-a663-955481c6e940"
          model_id: "810450774"
          event_name: "Andrea Bocelli | Romanza - 30th Anniversary World Tour 2026-05-30 20:00"
          sale_start: "2024-01-01"
